package lex

var kw_map = map[string]Token{
	"auto":     tok(AUTO),
	"break":    tok(BREAK),
	"case":     tok(CASE),
	"char":     tok(CHAR),
	"const":    tok(CONST),
	"continue": tok(CONTINUE),
	"default":  tok(DEFAULT),
	"do":       tok(DO),
	"double":   tok(DOUBLE),
	"else":     tok(ELSE),
	"enum":     tok(ENUM),
	"extern":   tok(EXTERN),
	"float":    tok(FLOAT),
	"for":      tok(FOR),
	"goto":     tok(GOTO),
	"if":       tok(IF),
	"int":      tok(INT),
	"long":     tok(LONG),
	"register": tok(REGISTER),
	"return":   tok(RETURN),
	"short":    tok(SHORT),
	"signed":   tok(SIGNED),
	"sizeof":   tok(SIZEOF),
	"static":   tok(STATIC),
	"struct":   tok(STRUCT),
	"switch":   tok(SWITCH),
	"typedef":  tok(TYPEDEF),
	"union":    tok(UNION),
	"unsigned": tok(UNSIGNED),
	"void":     tok(VOID),
	"volatile": tok(VOLATILE),
	"while":    tok(WHILE),
}
