// Code generated by "stringer -type=Toktype"; DO NOT EDIT.

package lex

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EOF-0]
	_ = x[ERR-1]
	_ = x[IDENT-2]
	_ = x[INT_CONST-3]
	_ = x[AUTO-4]
	_ = x[BREAK-5]
	_ = x[CASE-6]
	_ = x[CHAR-7]
	_ = x[CONST-8]
	_ = x[CONTINUE-9]
	_ = x[DEFAULT-10]
	_ = x[DO-11]
	_ = x[DOUBLE-12]
	_ = x[ELSE-13]
	_ = x[ENUM-14]
	_ = x[EXTERN-15]
	_ = x[FLOAT-16]
	_ = x[FOR-17]
	_ = x[GOTO-18]
	_ = x[IF-19]
	_ = x[INT-20]
	_ = x[LONG-21]
	_ = x[REGISTER-22]
	_ = x[RETURN-23]
	_ = x[SHORT-24]
	_ = x[SIGNED-25]
	_ = x[SIZEOF-26]
	_ = x[STATIC-27]
	_ = x[STRUCT-28]
	_ = x[SWITCH-29]
	_ = x[TYPEDEF-30]
	_ = x[UNION-31]
	_ = x[UNSIGNED-32]
	_ = x[VAR-33]
	_ = x[VOID-34]
	_ = x[VOLATILE-35]
	_ = x[WHILE-36]
	_ = x[LPAREN-37]
	_ = x[RPAREN-38]
	_ = x[LBRACE-39]
	_ = x[RBRACE-40]
	_ = x[LBRACKET-41]
	_ = x[RBRACKET-42]
	_ = x[LSHIFT-43]
	_ = x[RSHIFT-44]
	_ = x[GT-45]
	_ = x[LT-46]
	_ = x[GEQ-47]
	_ = x[LEQ-48]
	_ = x[EQ-49]
	_ = x[NEQ-50]
	_ = x[BAND-51]
	_ = x[BXOR-52]
	_ = x[BOR-53]
	_ = x[BCOMP-54]
	_ = x[AND-55]
	_ = x[OR-56]
	_ = x[QMARK-57]
	_ = x[INC-58]
	_ = x[DEC-59]
	_ = x[DOT-60]
	_ = x[ARROW-61]
	_ = x[MUL-62]
	_ = x[DIV-63]
	_ = x[MOD-64]
	_ = x[ADD-65]
	_ = x[SUB-66]
	_ = x[COMMA-67]
	_ = x[ASSIGN-68]
	_ = x[ADD_ASSIGN-69]
	_ = x[SUB_ASSIGN-70]
	_ = x[MUL_ASSIGN-71]
	_ = x[DIV_ASSIGN-72]
	_ = x[MOD_ASSIGN-73]
	_ = x[RS_ASSIGN-74]
	_ = x[LS_ASSIGN-75]
	_ = x[BA_ASSIGN-76]
	_ = x[XO_ASSIGN-77]
	_ = x[BO_ASSIGN-78]
	_ = x[SCOLON-79]
	_ = x[NOT-80]
	_ = x[ELLIP-81]
	_ = x[COLON-82]
}

const _Toktype_name = "EOFERRIDENTINT_CONSTAUTOBREAKCASECHARCONSTCONTINUEDEFAULTDODOUBLEELSEENUMEXTERNFLOATFORGOTOIFINTLONGREGISTERRETURNSHORTSIGNEDSIZEOFSTATICSTRUCTSWITCHTYPEDEFUNIONUNSIGNEDVARVOIDVOLATILEWHILELPARENRPARENLBRACERBRACELBRACKETRBRACKETLSHIFTRSHIFTGTLTGEQLEQEQNEQBANDBXORBORBCOMPANDORQMARKINCDECDOTARROWMULDIVMODADDSUBCOMMAASSIGNADD_ASSIGNSUB_ASSIGNMUL_ASSIGNDIV_ASSIGNMOD_ASSIGNRS_ASSIGNLS_ASSIGNBA_ASSIGNXO_ASSIGNBO_ASSIGNSCOLONNOTELLIPCOLON"

var _Toktype_index = [...]uint16{0, 3, 6, 11, 20, 24, 29, 33, 37, 42, 50, 57, 59, 65, 69, 73, 79, 84, 87, 91, 93, 96, 100, 108, 114, 119, 125, 131, 137, 143, 149, 156, 161, 169, 172, 176, 184, 189, 195, 201, 207, 213, 221, 229, 235, 241, 243, 245, 248, 251, 253, 256, 260, 264, 267, 272, 275, 277, 282, 285, 288, 291, 296, 299, 302, 305, 308, 311, 316, 322, 332, 342, 352, 362, 372, 381, 390, 399, 408, 417, 423, 426, 431, 436}

func (i Toktype) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Toktype_index)-1 {
		return "Toktype(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Toktype_name[_Toktype_index[idx]:_Toktype_index[idx+1]]
}
