// Code generated by "stringer -type=Toktype"; DO NOT EDIT.

package lex

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EOF-0]
	_ = x[IDENT-1]
	_ = x[INT_CONST-2]
	_ = x[AUTO-3]
	_ = x[BREAK-4]
	_ = x[CASE-5]
	_ = x[CHAR-6]
	_ = x[CONST-7]
	_ = x[CONTINUE-8]
	_ = x[DEFAULT-9]
	_ = x[DO-10]
	_ = x[DOUBLE-11]
	_ = x[ELSE-12]
	_ = x[ENUM-13]
	_ = x[EXTERN-14]
	_ = x[FLOAT-15]
	_ = x[FOR-16]
	_ = x[GOTO-17]
	_ = x[IF-18]
	_ = x[INT-19]
	_ = x[LONG-20]
	_ = x[REGISTER-21]
	_ = x[RETURN-22]
	_ = x[SHORT-23]
	_ = x[SIGNED-24]
	_ = x[SIZEOF-25]
	_ = x[STATIC-26]
	_ = x[STRUCT-27]
	_ = x[SWITCH-28]
	_ = x[TYPEDEF-29]
	_ = x[UNION-30]
	_ = x[UNSIGNED-31]
	_ = x[VAR-32]
	_ = x[VOID-33]
	_ = x[VOLATILE-34]
	_ = x[WHILE-35]
	_ = x[LPAREN-36]
	_ = x[RPAREN-37]
	_ = x[LBRACE-38]
	_ = x[RBRACE-39]
	_ = x[LBRACKET-40]
	_ = x[RBRACKET-41]
	_ = x[LSHIFT-42]
	_ = x[RSHIFT-43]
	_ = x[GT-44]
	_ = x[LT-45]
	_ = x[GEQ-46]
	_ = x[LEQ-47]
	_ = x[EQ-48]
	_ = x[NEQ-49]
	_ = x[BAND-50]
	_ = x[BXOR-51]
	_ = x[BOR-52]
	_ = x[BCOMP-53]
	_ = x[AND-54]
	_ = x[OR-55]
	_ = x[QMARK-56]
	_ = x[INC-57]
	_ = x[DEC-58]
	_ = x[DOT-59]
	_ = x[ARROW-60]
	_ = x[MUL-61]
	_ = x[DIV-62]
	_ = x[MOD-63]
	_ = x[ADD-64]
	_ = x[SUB-65]
	_ = x[COMMA-66]
	_ = x[ASSIGN-67]
	_ = x[ADD_ASSIGN-68]
	_ = x[SUB_ASSIGN-69]
	_ = x[MUL_ASSIGN-70]
	_ = x[DIV_ASSIGN-71]
	_ = x[MOD_ASSIGN-72]
	_ = x[RS_ASSIGN-73]
	_ = x[LS_ASSIGN-74]
	_ = x[BA_ASSIGN-75]
	_ = x[XO_ASSIGN-76]
	_ = x[BO_ASSIGN-77]
	_ = x[SCOLON-78]
	_ = x[NOT-79]
	_ = x[ELLIP-80]
	_ = x[COLON-81]
}

const _Toktype_name = "EOFIDENTINT_CONSTAUTOBREAKCASECHARCONSTCONTINUEDEFAULTDODOUBLEELSEENUMEXTERNFLOATFORGOTOIFINTLONGREGISTERRETURNSHORTSIGNEDSIZEOFSTATICSTRUCTSWITCHTYPEDEFUNIONUNSIGNEDVARVOIDVOLATILEWHILELPARENRPARENLBRACERBRACELBRACKETRBRACKETLSHIFTRSHIFTGTLTGEQLEQEQNEQBANDBXORBORBCOMPANDORQMARKINCDECDOTARROWMULDIVMODADDSUBCOMMAASSIGNADD_ASSIGNSUB_ASSIGNMUL_ASSIGNDIV_ASSIGNMOD_ASSIGNRS_ASSIGNLS_ASSIGNBA_ASSIGNXO_ASSIGNBO_ASSIGNSCOLONNOTELLIPCOLON"

var _Toktype_index = [...]uint16{0, 3, 8, 17, 21, 26, 30, 34, 39, 47, 54, 56, 62, 66, 70, 76, 81, 84, 88, 90, 93, 97, 105, 111, 116, 122, 128, 134, 140, 146, 153, 158, 166, 169, 173, 181, 186, 192, 198, 204, 210, 218, 226, 232, 238, 240, 242, 245, 248, 250, 253, 257, 261, 264, 269, 272, 274, 279, 282, 285, 288, 293, 296, 299, 302, 305, 308, 313, 319, 329, 339, 349, 359, 369, 378, 387, 396, 405, 414, 420, 423, 428, 433}

func (i Toktype) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Toktype_index)-1 {
		return "Toktype(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Toktype_name[_Toktype_index[idx]:_Toktype_index[idx+1]]
}
