(* 6.9 *)
translation_unit 
    = external_declaration
    | translation_unit, external_declaration
    ;

(* 6.9 *)
external_declaration
    = function_definition
    | declaration
    ;

(* 6.9.1 *)
function_definition
    = declaration_specifiers, declarator, [ declarator_list ], compound_statement
    ;

(* 6.9.1 *)
declaration_list
    = declaration
    | declaration_list, declaration
    ;

(* region declaration *)
(* 6.7 *)
declaration
    = declaration_specifiers, [ init_declarator_list ], ";"
    | static_assert_declaration
    ;

(* 6.7 *)
declaration_specifiers
    = storage_class_specifier, [ declaration_specifiers ]
    | type_specifier, [ declaration_specifiers ]
    | type_qualifier, [ declaration_specifiers ]
    | function_specifier, [ declaration_specifiers ]
    | alignment_specifier, [ declaration_specifiers ]
    ;

(* 6.7 *)
init_declarator_list
    = init_declarator
    | init_declarator_list, ",", init_declarator
    ;

(* 6.7 *)
init_declarator
    = declarator
    | declarator, [ "=", initializer ]
    ;

(* 6.7.1 *)
storage_class_specifier
    = "typedef" | "extern" | "static" | "_Thread_local" | "auto" | "register"
    ;

(* 6.7.2 *)
type_specifier
    = "void" | "char" | "short" | "int" | "long" | "float" | "double"
    | "signed" | "unsigned" | "_Bool" | "_Complex"
    | atomic_type_specifier
    | struct_or_union_specifier
    | enum_specifier
    | typedef_name
    ;

(* 6.7.2.1 *)
struct_or_union_specifier
    = struct_or_union, [ identifier ], "{", struct_declaration_list ,"}"
    | struct_or_union, identifier
    ;

(* 6.7.2.1 *)
struct_or_union
    = "struct" | "union"
    ;

(* 6.7.2.1 *)
struct_declaration_list
    = struct_declaration
    | struct_declaration_list, struct_declaration
    ;

(* 6.7.2.1 *)
struct_declaration
    = specifier_qualifier_list, [ struct_declarator_list ], ";"
    | static_assert_declaration
    ;

(* 6.7.2.1 *)
specifier_qualifier_list
    = type_specifier, [ specifier_qualifier_list ]
    | type_qualifier, [ specifier_qualifier_list ]
    | alignment_specifier, [ specifier_qualifier_list ]
    ;

(* 6.7.2.1 *)
struct_declarator_list
    = struct_declarator
    | struct_declarator_list, ",", struct_declarator
    ;

(* 6.7.2.1 *)
struct_declarator
    = declarator
    | [ declarator ], ":", constant_expression
    ;

(* 6.7.2.2 *)
enum_specifier
    = "enum", [ identifier ], "{", enumerator_list, "}"
    | "enum", [ identifier ], "{", enumerator_list,  ",", "}"
    | "enum", identifier
    ;

(* 6.7.2.2 *)
enumerator_list
    = enumerator
    | enumerator_list, ",", enumerator
    ;

(* 6.7.2.4 *)
atomic_type_specifier
    = "_Atomic", "(", type_name ,")"
    ;

(* 6.7.3 *)
type_qualifier
    = "const" | "restrict" | "volatile" | "_Atomic"
    ;

(* 6.7.4 *)
function_specifier
    = "inline" | "_Noreturn"
    ;

(* 6.7.5 *)
alignment_specifier
    = "_Alignas", "(", type_name ,")"
    | "_Alignas", "(", constant_expression, ")"
    ;

(* region declarator *)
(* 6.7.6 *)
declarator
    = [ pointer ], direct_declarator
    ;
(* 6.7.6 *)
direct_declarator
    = identifier
    | "(", declarator ,")"
    | direct_declarator, 
        "[", [ type_qualifier_list ], [ assignment_expression ], "]"
    | direct_declarator,
        "[", "static", [ type_qualifier_list ], assignment_expression, "]"
    | direct_declarator,
        "[", type_qualifier_list, "static", assignment_expression, "]"
    | direct_declarator, 
        "[", [ type_qualifier_list ], "*", "]"
    | direct_declarator, "(", parameter_type_list, ")"
    | direct_declarator, "(", [ identifier_list ], ")"
    ;

(* 6.7.6 *)
pointer
    = "*", [ type_qualifier_list ]
    | "*", [ type_qualifier_list ], pointer
    ;

(* 6.7.6 *)
type_qualifier_list
    = type_qualifier
    | type_qualifier_list, type_qualifier
    ;

(* 6.7.6 *)
parameter_type_list
    = parameter_list
    | parameter_list, ",", "..."
    ;

(* 6.7.6 *)
parameter_list
    = parameter_declaration
    | parameter_list, ",", parameter_declaration
    ;

(* 6.7.6 *)
parameter_declaration
    = declaration_specifiers, declarator
    | declaration_specifiers, [ abstract_declarator ]
    ;

(* 6.7.6 *)
identifier_list
    = identifier
    | identifier_list, ",", identifier
    ;

(* 6.7.7 *)
type_name
    = specifier_qualifier_list, [ abstract_declarator ]
    ;

(* 6.7.7 *)
abstract_declarator
    = pointer,
    | [ pointer ], direct_abstract_declarator
    ;


(* endregion *)

(* endregion *)