// Code generated by "stringer -type=BinaryOpType"; DO NOT EDIT.

package asm

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ADD-0]
	_ = x[SUB-1]
	_ = x[MUL-2]
}

const _BinaryOpType_name = "ADDSUBMUL"

var _BinaryOpType_index = [...]uint8{0, 3, 6, 9}

func (i BinaryOpType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_BinaryOpType_index)-1 {
		return "BinaryOpType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BinaryOpType_name[_BinaryOpType_index[idx]:_BinaryOpType_index[idx+1]]
}
