// Code generated by "stringer -type=Condcode"; DO NOT EDIT.

package asm

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[E-0]
	_ = x[NE-1]
	_ = x[G-2]
	_ = x[GE-3]
	_ = x[L-4]
	_ = x[LE-5]
}

const _Condcode_name = "ENEGGELLE"

var _Condcode_index = [...]uint8{0, 1, 3, 4, 6, 7, 9}

func (i Condcode) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Condcode_index)-1 {
		return "Condcode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Condcode_name[_Condcode_index[idx]:_Condcode_index[idx+1]]
}
