// Code generated by "stringer -type=UnaryOpType"; DO NOT EDIT.

package asm

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NEG-0]
	_ = x[NOT-1]
	_ = x[LOGICAL_NOT-2]
}

const _UnaryOpType_name = "NEGNOTLOGICAL_NOT"

var _UnaryOpType_index = [...]uint8{0, 3, 6, 17}

func (i UnaryOpType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_UnaryOpType_index)-1 {
		return "UnaryOpType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _UnaryOpType_name[_UnaryOpType_index[idx]:_UnaryOpType_index[idx+1]]
}
